In [1]:
import tensorflow as tf
print("TensorFlow version: {}".format(tf.__version__))
print("Keras version: {}".format(tf.keras.__version__))

TensorFlow version: 2.2.0
Keras version: 2.3.0-tf


In [2]:
variable = tf.Variable([3, 3])
if tf.test.is_gpu_available():
    print('GPU')
    print('GPU #0?')
    print(variable.device.endswith('GPU:0'))
else:
    print('CPU')

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
GPU
GPU #0?
False


In [3]:
import tensorflow as tf
if tf.test.gpu_device_name():
    print('Default GPU Device:{}'.format(tf.test.gpu_device_name()))
else:
    print("Please install GPU version of TF")

Default GPU Device:/device:GPU:0


In [4]:
#Tensor Constant
ar = tf.constant(42)
ar

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [5]:
ar.numpy()

42

In [6]:
ar1 = tf.constant(1, dtype = tf.int64)
ar1

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [7]:
ar2 = tf.constant([[4,2],[9,5]])
print(ar2)

tf.Tensor(
[[4 2]
 [9 5]], shape=(2, 2), dtype=int32)


In [9]:
print('shape:',ar2.shape)
print(ar2.dtype)

shape: (2, 2)
<dtype: 'int32'>


In [10]:
#Ones
print(tf.ones(shape=(2,3)))

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [11]:
#Zeros
print(tf.zeros(shape=(3,2)))

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [13]:
#Add
import tensorflow as tf
c1 = tf.constant([[3,4,5], [1,2,3]]);tf
c2 = tf.constant([[1,2,3], [1,2,3]]);
result = tf.add(c1, c2);
print(result)

tf.Tensor(
[[4 6 8]
 [2 4 6]], shape=(2, 3), dtype=int32)


In [14]:

tf.random.normal(shape=(2,2),mean=0,stddev=1.0)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-1.117243  , -1.8938231 ],
       [-0.11987682, -2.853949  ]], dtype=float32)>

In [15]:
tf.random.uniform(shape=(2,2),minval=0,maxval=10,dtype=tf.int32)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 3],
       [4, 2]])>

In [16]:
#Variables
var0 = 24 # python variable
var1 = tf.Variable(42) # rank 0 tensor
var2 = tf.Variable([ [ [0., 1., 2.], [3., 4., 5.] ], [ [6., 7., 8.], [9., 10., 11.] ] ]) #rank 3 tensor
var0, var1, var2

(24,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=42>,
 <tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
 array([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],
 
        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]], dtype=float32)>)

In [17]:
#Datatype declaration - Explicitly
float_var64 = tf.Variable(89, dtype = tf.float64)
float_var64.dtype

tf.float64

In [18]:
#Reassign a Variable - var.assign()
var_reassign = tf.Variable(89.)
var_reassign

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=89.0>

In [19]:
var_reassign.assign(98.)
var_reassign

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=98.0>

In [20]:
initial_value = tf.random.normal(shape=(2,2))
a = tf.Variable(initial_value)
print(a)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 0.20591934,  0.5263343 ],
       [-0.20316957, -0.38202712]], dtype=float32)>


In [24]:
new_value = tf.random.normal(shape=(2, 2))
a.assign(new_value)
for i in range(2):
    for j in range(2):
        assert a[i, j] == new_value[i, j]
        print(i,j)

0 0
0 1
1 0
1 1


In [28]:
#Shaping a tensor
tensor = tf.Variable([ [ [10., 11., 12.], [13., 14., 15.] ], [ [16., 17., 18.], [19., 20., 21.] ] ]) # tensor variable
print(tensor.shape)

(2, 2, 3)


In [29]:
#Mathematical operations
a = tf.random.normal(shape=(2,2))
b = tf.random.normal(shape=(2,2))
c = a + b
d = tf.square(c)
e = tf.exp(c)
print(a)
print(b)
print(c)
print(d)
print(e)

tf.Tensor(
[[ 1.4734672   0.14266592]
 [ 0.5423324  -2.0267577 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-0.7540722  0.832197 ]
 [-0.4607971 -1.2817942]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 0.71939504  0.97486293]
 [ 0.08153531 -3.3085518 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[5.1752925e-01 9.5035774e-01]
 [6.6480068e-03 1.0946515e+01]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[2.0531907 2.6508038]
 [1.0849515 0.0365691]], shape=(2, 2), dtype=float32)
